[tool.poetry]
name = "fletrt"
version = "0.0.1"
description = "Simple routing for the Flet framework."
authors = ["PedroG022"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
